version: '2'
volumes:
  # chromium profiles
  chromiumData:
  # audio
  pulse:
services:
  # the audio server based on pulseaudio
  audio:
    restart: always
    image: balenablocks/audio:intel-nuc
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - '127.0.0.1:4317:4317'
    volumes:
      - 'pulse:/run/pulse'
  chromium:
    restart: always
    build: ./chromium
    privileged: true
    network_mode: host
    expose:
      - 9222-9230
    depends_on:
      - audio
    volumes:
      - 'chromiumData:/home/displayuser/chromium'
      - 'pulse:/run/pulse'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
